// <auto-generated />
using System;
using ChefApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ChefApp.Migrations
{
    [DbContext(typeof(ChefAppContext))]
    [Migration("20240516231315_added_Duration_Column_To_Instructions_Table")]
    partial class added_Duration_Column_To_Instructions_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ChefApp.Models.DbModels.Chef", b =>
                {
                    b.Property<int>("ChefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChefId"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ChefId");

                    b.ToTable("Chefs");

                    b.HasData(
                        new
                        {
                            ChefId = 1,
                            FirstName = "Gordon",
                            LastName = "Ramsay"
                        },
                        new
                        {
                            ChefId = 2,
                            FirstName = "Jamie",
                            LastName = "Oliver"
                        },
                        new
                        {
                            ChefId = 3,
                            FirstName = "Wolfgang",
                            LastName = "Puck"
                        },
                        new
                        {
                            ChefId = 4,
                            FirstName = "Alice",
                            LastName = "Waters"
                        },
                        new
                        {
                            ChefId = 5,
                            FirstName = "Thomas",
                            LastName = "Keller"
                        },
                        new
                        {
                            ChefId = 6,
                            FirstName = "Emeril",
                            LastName = "Lagasse"
                        });
                });

            modelBuilder.Entity("ChefApp.Models.DbModels.Instruction", b =>
                {
                    b.Property<int>("InstructionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstructionId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeOnly?>("Duration")
                        .HasColumnType("time");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("InstructionId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Instructions");

                    b.HasData(
                        new
                        {
                            InstructionId = 1,
                            Description = "Prepare beef",
                            OrderId = 1,
                            RecipeId = 1
                        },
                        new
                        {
                            InstructionId = 2,
                            Description = "Wrap in puff pastry",
                            OrderId = 2,
                            RecipeId = 1
                        },
                        new
                        {
                            InstructionId = 3,
                            Description = "Bake",
                            OrderId = 3,
                            RecipeId = 1
                        },
                        new
                        {
                            InstructionId = 4,
                            Description = "Cook pasta",
                            OrderId = 1,
                            RecipeId = 2
                        },
                        new
                        {
                            InstructionId = 5,
                            Description = "Prepare sauce",
                            OrderId = 2,
                            RecipeId = 2
                        },
                        new
                        {
                            InstructionId = 6,
                            Description = "Combine and serve",
                            OrderId = 3,
                            RecipeId = 2
                        },
                        new
                        {
                            InstructionId = 7,
                            Description = "Prepare tuna",
                            OrderId = 1,
                            RecipeId = 3
                        },
                        new
                        {
                            InstructionId = 8,
                            Description = "Roll sushi",
                            OrderId = 2,
                            RecipeId = 3
                        },
                        new
                        {
                            InstructionId = 9,
                            Description = "Serve with soy sauce",
                            OrderId = 3,
                            RecipeId = 3
                        },
                        new
                        {
                            InstructionId = 10,
                            Description = "Prepare lentils",
                            OrderId = 1,
                            RecipeId = 4
                        },
                        new
                        {
                            InstructionId = 11,
                            Description = "Cook lentils",
                            OrderId = 2,
                            RecipeId = 4
                        },
                        new
                        {
                            InstructionId = 12,
                            Description = "Serve hot",
                            OrderId = 3,
                            RecipeId = 4
                        },
                        new
                        {
                            InstructionId = 13,
                            Description = "Season chicken",
                            OrderId = 1,
                            RecipeId = 5
                        },
                        new
                        {
                            InstructionId = 14,
                            Description = "Roast chicken",
                            OrderId = 2,
                            RecipeId = 5
                        },
                        new
                        {
                            InstructionId = 15,
                            Description = "Serve with vegetables",
                            OrderId = 3,
                            RecipeId = 5
                        },
                        new
                        {
                            InstructionId = 16,
                            Description = "Prepare bananas",
                            OrderId = 1,
                            RecipeId = 6
                        },
                        new
                        {
                            InstructionId = 17,
                            Description = "Cook with butter and sugar",
                            OrderId = 2,
                            RecipeId = 6
                        },
                        new
                        {
                            InstructionId = 18,
                            Description = "Serve with ice cream",
                            OrderId = 3,
                            RecipeId = 6
                        });
                });

            modelBuilder.Entity("ChefApp.Models.DbModels.Recipe", b =>
                {
                    b.Property<int>("RecipeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecipeId"));

                    b.Property<int>("ChefId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RecipeId");

                    b.HasIndex("ChefId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            RecipeId = 1,
                            ChefId = 1,
                            Name = "Beef Wellington"
                        },
                        new
                        {
                            RecipeId = 2,
                            ChefId = 2,
                            Name = "Pasta Carbonara"
                        },
                        new
                        {
                            RecipeId = 3,
                            ChefId = 3,
                            Name = "Spicy Tuna Rolls"
                        },
                        new
                        {
                            RecipeId = 4,
                            ChefId = 4,
                            Name = "Lentil Soup"
                        },
                        new
                        {
                            RecipeId = 5,
                            ChefId = 5,
                            Name = "Roast Chicken"
                        },
                        new
                        {
                            RecipeId = 6,
                            ChefId = 6,
                            Name = "Bananas Foster"
                        });
                });

            modelBuilder.Entity("ChefApp.Models.DbModels.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnOrder(0);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasColumnOrder(4);

                    b.Property<int>("PublisherId")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.Property<int>("SubscriberId")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("SubscriptionDate")
                        .HasColumnType("datetime2")
                        .HasColumnOrder(3);

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasColumnOrder(5);

                    b.HasKey("SubscriptionId");

                    b.HasIndex("PublisherId");

                    b.HasIndex("SubscriberId");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            SubscriptionId = 1,
                            Amount = 99.99m,
                            PublisherId = 1,
                            SubscriberId = 3,
                            SubscriptionDate = new DateTime(2024, 5, 17, 0, 13, 14, 967, DateTimeKind.Local).AddTicks(7809),
                            SubscriptionType = "Monthly"
                        },
                        new
                        {
                            SubscriptionId = 2,
                            Amount = 99.99m,
                            PublisherId = 1,
                            SubscriberId = 4,
                            SubscriptionDate = new DateTime(2024, 5, 17, 0, 13, 14, 967, DateTimeKind.Local).AddTicks(7871),
                            SubscriptionType = "Monthly"
                        },
                        new
                        {
                            SubscriptionId = 3,
                            Amount = 99.99m,
                            PublisherId = 1,
                            SubscriberId = 5,
                            SubscriptionDate = new DateTime(2024, 5, 17, 0, 13, 14, 967, DateTimeKind.Local).AddTicks(7873),
                            SubscriptionType = "Monthly"
                        },
                        new
                        {
                            SubscriptionId = 4,
                            Amount = 199.99m,
                            PublisherId = 2,
                            SubscriberId = 4,
                            SubscriptionDate = new DateTime(2024, 5, 17, 0, 13, 14, 967, DateTimeKind.Local).AddTicks(7875),
                            SubscriptionType = "Yearly"
                        },
                        new
                        {
                            SubscriptionId = 5,
                            Amount = 199.99m,
                            PublisherId = 2,
                            SubscriberId = 5,
                            SubscriptionDate = new DateTime(2024, 5, 17, 0, 13, 14, 967, DateTimeKind.Local).AddTicks(7877),
                            SubscriptionType = "Yearly"
                        },
                        new
                        {
                            SubscriptionId = 6,
                            Amount = 199.99m,
                            PublisherId = 2,
                            SubscriberId = 6,
                            SubscriptionDate = new DateTime(2024, 5, 17, 0, 13, 14, 967, DateTimeKind.Local).AddTicks(7879),
                            SubscriptionType = "Yearly"
                        });
                });

            modelBuilder.Entity("ChefApp.Models.DbModels.Instruction", b =>
                {
                    b.HasOne("ChefApp.Models.DbModels.Recipe", "Recipe")
                        .WithMany("Instructions")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("ChefApp.Models.DbModels.Recipe", b =>
                {
                    b.HasOne("ChefApp.Models.DbModels.Chef", "Chef")
                        .WithMany("Recipes")
                        .HasForeignKey("ChefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chef");
                });

            modelBuilder.Entity("ChefApp.Models.DbModels.Subscription", b =>
                {
                    b.HasOne("ChefApp.Models.DbModels.Chef", "Publisher")
                        .WithMany("PublishedSubscriptions")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ChefApp.Models.DbModels.Chef", "Subscriber")
                        .WithMany("SubscribedTo")
                        .HasForeignKey("SubscriberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Publisher");

                    b.Navigation("Subscriber");
                });

            modelBuilder.Entity("ChefApp.Models.DbModels.Chef", b =>
                {
                    b.Navigation("PublishedSubscriptions");

                    b.Navigation("Recipes");

                    b.Navigation("SubscribedTo");
                });

            modelBuilder.Entity("ChefApp.Models.DbModels.Recipe", b =>
                {
                    b.Navigation("Instructions");
                });
#pragma warning restore 612, 618
        }
    }
}
